version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: . 
      dockerfile: webapp/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "7zc7agecM6EmRmoiQmvYF5k3v"
      ACCEPT_EULA: "Y"