version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: webapp/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "7zc7agecM6EmRmoiQmvYF5k3v"
      ACCEPT_EULA: "Y"
  orbackend:
    build:
      context: .
      dockerfile: orbackend/docker/Dockerfile